### ISSUE TITLE
exception on sendMessage call

### ISSUE THREAD

**Issue by fedulovivan** [alik0211/mtproto-core#126]
Attempt to send message
```js
const { MTProto } = require('@mtproto/core');

const api_id = '###';
const api_hash = '###';

const mtproto = new MTProto({
  api_id,
  api_hash,
});

mtproto.call('messages.sendMessage', {
    peer: '###',
    message: 'Test',
    random_id: (new Date).valueOf(),
}).then(console.log).catch(console.error);
```
Fails with non-relevant exception:
```sh
johnny@macmini:~/Projects/mhz19-next$ node telegram-test.js
Auth data is located in /home/johnny/.local/share/@mtproto/core
TypeError: Cannot read property 'call' of undefined
    at Counter.predicate (/home/johnny/Projects/mhz19-next/node_modules/@mtproto/core/src/tl/counter/index.cjs:101:8)
    at Counter.messages.sendMessage (/home/johnny/Projects/mhz19-next/node_modules/@mtproto/core/src/tl/builder/index.cjs:5402:10)
    at Counter.predicate (/home/johnny/Projects/mhz19-next/node_modules/@mtproto/core/src/tl/counter/index.cjs:101:8)
    at Counter.initConnection (/home/johnny/Projects/mhz19-next/node_modules/@mtproto/core/src/tl/builder/index.cjs:5625:10)
    at Counter.predicate (/home/johnny/Projects/mhz19-next/node_modules/@mtproto/core/src/tl/counter/index.cjs:101:8)
    at Counter.invokeWithLayer (/home/johnny/Projects/mhz19-next/node_modules/@mtproto/core/src/tl/builder/index.cjs:5670:10)
    at new Counter (/home/johnny/Projects/mhz19-next/node_modules/@mtproto/core/src/tl/counter/index.cjs:7:8)
    at new Serializer (/home/johnny/Projects/mhz19-next/node_modules/@mtproto/core/src/tl/serializer/index.cjs:7:21)
    at RPC.call (/home/johnny/Projects/mhz19-next/node_modules/@mtproto/core/src/rpc/index.cjs:581:24)
    at /home/johnny/Projects/mhz19-next/node_modules/@mtproto/core/src/rpc/index.cjs:389:12
```

**Comment by d0vdr0xx** [comment]
Same issue here

**Comment by ArkIv** [comment]
1) // checking authentication status
https://stackoverflow.com/questions/64594824/mtproto-core-telegram-replay-to-another-channel
2) **peer: {
        _: "inputPeerUser",
        user_id: user_id,
      },**

**Comment by tharindusathis** [comment]
Same issue here. Any workaround??

**Comment by alik0211** [comment]
@fedulovivan you have incorrect parameters for the call method. `peer` is not a string - https://core.telegram.org/method/messages.sendMessage

I plan to improve the error message and make the error useful
