### ISSUE TITLE
upload.getFile UnhandledPromiseRejectionWarning: #<Object>

### ISSUE THREAD

**Issue by ax333l** [alik0211/mtproto-core#127]
Throws this error only when calling upload.getFile(). Tried different params same result. If no '_' provided throw undefined error. Node.js 14.
```
const mtproto = new MTProto({
    api_id,
    api_hash,
});


const file = await mtproto.call("upload.getFile", {
    cdn_supported: true,
    precise: true,
    offset: 0,
    limit: 4096,
    location: {
        _: "inputFileLocation",
        big: true,
        volume_id: "200123900081",
        local_id: 83792,
        peer: {
        '_': 'inputPeerUser',
        user_id: 1231195778,
        access_hash: "2500466316018771206"
        },
    },
});
```
```
(node:13392) UnhandledPromiseRejectionWarning: #<Object>
    at emitUnhandledRejectionWarning (internal/process/promises.js:170:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:13392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13392) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, 
promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.  
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by 1AndOnlyPika** [comment]
I am using messages.getAllChats and is getting the same issue.

**Comment by will2022** [comment]
It looks like "inputFileLocation" is deprecated. https://core.telegram.org/type/InputFileLocation

**Comment by ax333l** [comment]
> It looks like "inputFileLocation" is deprecated. https://core.telegram.org/type/InputFileLocation

So is there a way to download a file from a channel?

**Comment by alik0211** [comment]
@ax333l use official docs - https://core.telegram.org/api/files

Or wait until I write the guide
