### ISSUE TITLE
TypeError: Cannot read property 'resolve' of undefined

### ISSUE THREAD

**Issue by atiquefiroz** [alik0211/mtproto-core#168]
`const result = plainDeserializer.predicate();`
`this.handleDecryptedMessage(result, { messageId, seqNo });`

should the call to the function be:
`await this.handleDecryptedMessage(result, { messageId, seqNo });`

and similar for the:
`message.messages.forEach((message) => {
        this.handleDecryptedMessage(message.body, {
          messageId: message.msg_id,
     });
});`

**Comment by alik0211** [comment]
Please attach a sample code so that I can reproduce the error

**Comment by pogudin-sergey** [comment]
I have a similar problem:
`TypeError: Cannot read property 'resolve' of undefined at RPC.handleDecryptedMessage (/var/www/telegram/node_modules/@mtproto/core/src/rpc/index.js:552:21) at /var/www/telegram/node_modules/@mtproto/core/src/rpc/index.js:473:14 at Array.forEach (<anonymous>) at RPC.handleDecryptedMessage (/var/www/telegram/node_modules/@mtproto/core/src/rpc/index.js:472:24) at RPC.handleEncryptedMessage (/var/www/telegram/node_modules/@mtproto/core/src/rpc/index.js:451:10) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:93:5)`
