### ISSUE TITLE
Problem with messages.searchGlobal & messages.search

### ISSUE THREAD

**Issue by pogudin-sergey** [alik0211/mtproto-core#202]
On call messages.searchGlobal or messages.search return exception:
```
err: TypeError: Cannot read property '_' of undefined
       at Counter.predicate (./node_modules/@mtproto/core/src/tl/counter/index.js:99:34)
       at Counter.messages.search (./node_modules/@mtproto/core/src/tl/builder/index.js:5354:10)
       at Counter.predicate (./node_modules/@mtproto/core/src/tl/counter/index.js:101:8)
       at Counter.initConnection (./node_modules/@mtproto/core/src/tl/builder/index.js:5625:10)
       at Counter.predicate (./node_modules/@mtproto/core/src/tl/counter/index.js:101:8)
       at Counter.invokeWithLayer (./node_modules/@mtproto/core/src/tl/builder/index.js:5670:10)
       at new Counter (./node_modules/@mtproto/core/src/tl/counter/index.js:7:8)
       at new Serializer (./node_modules/@mtproto/core/src/tl/serializer/index.js:7:21)
       at RPC.call (./node_modules/@mtproto/core/src/rpc/index.js:591:24)
       at Object.call (./node_modules/@mtproto/core/src/index.js:106:32)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at async Telegram.call (./lib/services/telegram.js:56:14)
       at async exports.search (./lib/api/message-search/index.js:27:20)
```

Example:
```js
mtproto.call('messages.searchGlobal', {
      q: "some string here",
      filter: {
            _: 'inputMessagesFilterEmpty',
      },
});
```

Problem in builder sheme? How to resolve?

**Comment by pogudin-sergey** [comment]
Resolved by right params:
```js
const search = await client.call('messages.searchGlobal', {
      q,
      filter: {
        _: 'inputMessagesFilterEmpty',
      },
      offset_peer: {
        _: 'inputPeerEmpty',
      },
});```
