### ISSUE TITLE
Error: EPERM: operation not permitted, rename

### ISSUE THREAD

**Issue by vmail** [alik0211/mtproto-core#260]
Hi, I get the following error

 Error: EPERM: operation not permitted, rename 'D:\Development\1.json.2192667871' -> 'D:\Development\1.json'
      at Object.renameSync (node:fs:980:3)
      at Function.writeFileSync [as sync] (D:\Development\node_modules\write-file-atomic\index.js:244:8)
      at Configstore.set all [as all] (D:\Development\node_modules\configstore\index.js:61:20)
      at Configstore.set (D:\Development\node_modules\configstore\index.js:91:12)
      at Storage.set (D:\Development\node_modules\@mtproto\core\src\storage\index.js:12:44)
      at RPC.setStorageItem (D:\Development\node_modules\@mtproto\core\src\rpc\index.js:772:33)
      at RPC.handleDecryptedMessage (D:\Development\node_modules\@mtproto\core\src\rpc\index.js:485:20)
      at RPC.handleEncryptedMessage (D:\Development\node_modules\@mtproto\core\src\rpc\index.js:451:10)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

I believe the error is coming from this line, the error happens at random.

new MTProto({
  storageOptions: {
    path: path.resolve(__dirname, './1.json'),
  },
});

I belive that this is why I have to keep entering the phone code every time the code starts

**Comment by vmail** [comment]
This error was fixed by disabling the backup software.

The only problem I have now is that I have to keep entering the phone code every time I start node. The storage file is being written to but it looks like it not being looked at at the start

**Comment by darkblazeGG** [comment]
I got the same problem on my server, reinstall OS, tried other cases, how did you disabled backup storage in mtproto?

**Comment by shalevc1098** [comment]
i have this too. how do i fix that?
