### ISSUE TITLE
Error when call "messages.getDialogs". 

### ISSUE THREAD

**Issue by flaviolacer** [alik0211/mtproto-core#39]
Seems that there is a bug when you try to call messages.getDialogs:

function call:

`// handling updates
client.updates.on('updateShortMessage', message => {
    console.log("changed update:", message);
    // get messages
    client.call('messages.getDialogs', {
        limit: 100
    }).then(results => {
        console.log("dialog results", results);
    });
});`

error:

`(node:8394) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_' of undefined
    at TLSerializer.predicate (/Users/flaviolacer/Projects/edi-telegram/node_modules/@mtproto/core/src/tl/serializer/index.cjs:130:71)
    at /Users/flaviolacer/Projects/edi-telegram/node_modules/@mtproto/core/src/tl/serializer/index.cjs:81:12
    at Array.forEach (<anonymous>)
    at TLSerializer.method (/Users/flaviolacer/Projects/edi-telegram/node_modules/@mtproto/core/src/tl/serializer/index.cjs:68:23)
    at RPC.call (/Users/flaviolacer/Projects/edi-telegram/node_modules/@mtproto/core/src/rpc/index.cjs:463:16)
    at MTProto.call (/Users/flaviolacer/Projects/edi-telegram/node_modules/@mtproto/core/src/index.cjs:72:28)
`

**Comment by somgupta13** [comment]
actually u need to pass all the parameter which are madatory just an example for sendmessage` mtproto.call('messages.sendMessage',{
				peer:{
					_ :'inputPeerUser',
					user_id:1057346232,
					access_hash:0							 
				},
				message:"hiii",
				random_id:6788
				
			}).then(result=>{console.log(result);});`

**Comment by anhnhoktvn** [comment]
And by the way, could someone tell me how to do following things:
- Get chats of main chat list.
- Send message to a chat
- Get group info

**Comment by flaviolacer** [comment]
Thanks! worked but the parameter is different! Looked at the scheme.

```
mtproto.call('messages.getDialogs', {
            limit: 100,
            offset_peer : {
                _: 'inputPeerEmpty'
            }
        })
```
