### ISSUE TITLE
Error at start up

### ISSUE THREAD

**Issue by Amantel** [alik0211/mtproto-core#56]
Steps: 
1. `npm i @mtproto/core -E`
2. used example code
3. launched
4. got an error: `Error: ENOENT: no such file or directory, mkdir '/home/tel/.local/share/@mtproto/core'`

**Comment by Amantel** [comment]
Full error
```
Error: ENOENT: no such file or directory, mkdir '/home/tel/.local/share/@mtproto/core'
    at Object.fs.mkdirSync (fs.js:892:18)
    at LocalStorage._init (/home/tel/Desktop/Projects/CC/node_modules/node-localstorage/LocalStorage.js:183:14)
    at new LocalStorage (/home/tel/Desktop/Projects/CC/node_modules/node-localstorage/LocalStorage.js:124:12)
    at Object.<anonymous> (/home/tel/Desktop/Projects/CC/node_modules/@mtproto/core/src/storage/local/index.cjs:10:22)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
```

**Comment by alik0211** [comment]
@Amantel try create folder `/home/tel/.local/share/@mtproto/core`

**Comment by Amantel** [comment]
That fixed the issue, thanks! Can you provide some info why the error happened? 

Aaah, I see the auth data is stored there, right?

**Comment by alik0211** [comment]
@Amantel right. This folder contains the auth information

This error occurred because [`node-localstorage`](https://github.com/alik0211/mtproto-core/blob/master/src/storage/local/index.js) tried to open a non-existent folder
