### ISSUE TITLE
TextEncoder is not defined error

### ISSUE THREAD

**Issue by kkarloe** [alik0211/mtproto-core#66]
Hi,
I created sample app using your quick start guide

```
const api_id = config.get('Telegram.ApiID');
const api_hash = config.get('Telegram.ApiHash');

// 1. Create an instance
const mtproto = new MTProto({
  api_id,
  api_hash,
});

// 2. Get the user country code
mtproto.call('help.getNearestDc').then(result => {
  console.log(`country:`, result.country);
});
```

however I'm getting the following error:

```
(node:38384) UnhandledPromiseRejectionWarning: ReferenceError: TextEncoder is not defined
    at TLSerializer.string (E:\git\TelegramApp1\node_modules\@mtproto\core\src\tl\serializer\index.cjs:210:21)
    at TLSerializer.predicate (E:\git\TelegramApp1\node_modules\@mtproto\core\src\tl\serializer\index.cjs:102:21)
    at methodData.params.forEach.paramData (E:\git\TelegramApp1\node_modules\@mtproto\core\src\tl\serializer\index.cjs:81:12)
    at Array.forEach (<anonymous>)
    at TLSerializer.method (E:\git\TelegramApp1\node_modules\@mtproto\core\src\tl\serializer\index.cjs:68:23)
    at RPC.call (E:\git\TelegramApp1\node_modules\@mtproto\core\src\rpc\index.cjs:575:16)
    at messagesWaitAuth.forEach.message (E:\git\TelegramApp1\node_modules\@mtproto\core\src\rpc\index.cjs:388:12)
    at Array.forEach (<anonymous>)
    at RPC.sendWaitMessages (E:\git\TelegramApp1\node_modules\@mtproto\core\src\rpc\index.cjs:386:27)
    at RPC.handleTransportOpen (E:\git\TelegramApp1\node_modules\@mtproto\core\src\rpc\index.cjs:96:12)
    at TCP.emit (events.js:182:13)
    at TCP.handleConnect (E:\git\TelegramApp1\node_modules\@mtproto\core\src\transport\tcp\index.cjs:82:10)
(node:38384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:38384) UnhandledPromiseRejectionWarning: ReferenceError: TextEncoder is not defined
    at TLSerializer.string (E:\git\TelegramApp1\node_modules\@mtproto\core\src\tl\serializer\index.cjs:210:21)
    at TLSerializer.predicate (E:\git\TelegramApp1\node_modules\@mtproto\core\src\tl\serializer\index.cjs:102:21)
    at methodData.params.forEach.paramData (E:\git\TelegramApp1\node_modules\@mtproto\core\src\tl\serializer\index.cjs:81:12)
    at Array.forEach (<anonymous>)
    at TLSerializer.method (E:\git\TelegramApp1\node_modules\@mtproto\core\src\tl\serializer\index.cjs:68:23)
    at RPC.call (E:\git\TelegramApp1\node_modules\@mtproto\core\src\rpc\index.cjs:575:16)
    at RPC.handleTransportOpen (E:\git\TelegramApp1\node_modules\@mtproto\core\src\rpc\index.cjs:99:12)
    at TCP.emit (events.js:182:13)
    at TCP.handleConnect (E:\git\TelegramApp1\node_modules\@mtproto\core\src\transport\tcp\index.cjs:82:10)
(node:38384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

```

Is there any additional setup required?

**Comment by alik0211** [comment]
Node js version must be 12 or higher - https://github.com/alik0211/mtproto-core/blob/master/package.json#L32-L34

**Comment by khoazero123** [comment]
I use node version 14.16 still get same error.
