### ISSUE TITLE
Cannot read property '_' of undefined

### ISSUE THREAD

**Issue by razenization** [alik0211/mtproto-core#76]
I'm trying to implement a code shown in the example with a slight change, in particular using other method: 'messages.getDialogs'.
I'm receiving this traceback:
```
(node:24636) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_' of undefined
    at TLSerializer.predicate (C:\Users\react\projects\tgarky\node_modules\@mtproto\core\src\tl\serializer\index.cjs:132:71)
    at C:\Users\react\projects\tgarky\node_modules\@mtproto\core\src\tl\serializer\index.cjs:81:12
    at Array.forEach (<anonymous>)
    at TLSerializer.method (C:\Users\react\projects\tgarky\node_modules\@mtproto\core\src\tl\serializer\index.cjs:68:23)
    at RPC.call (C:\Users\react\projects\tgarky\node_modules\@mtproto\core\src\rpc\index.cjs:588:29)
    at C:\Users\react\projects\tgarky\node_modules\@mtproto\core\src\rpc\index.cjs:388:12
    at Array.forEach (<anonymous>)
    at RPC.sendWaitMessages (C:\Users\react\projects\tgarky\node_modules\@mtproto\core\src\rpc\index.cjs:386:27)
    at RPC.handleTransportOpen (C:\Users\react\projects\tgarky\node_modules\@mtproto\core\src\rpc\index.cjs:96:12)
(Use `node --trace-warnings ...` to show where the warning was created)
```

Sorry for bothering, but I really would like to know what am I doing wrong :(
I checked the file which is throwing an exception and wrote some console.logs. The file is index.cjs in serializer dir.

```
console.log(predicate);
console.log(type);
console.log(Array.isArray(predicate));
console.log(type.substr(0, 6).toLowerCase() == 'vector');
```
returns: 
```
undefined
InputPeer
false
false
```
and throws the exception shown above.

**Comment by alik0211** [comment]
Dublicate #39. Solution - https://github.com/alik0211/mtproto-core/issues/39#issuecomment-623125987
