### ISSUE TITLE
New error after a certain time

### ISSUE THREAD

**Issue by flaviolacer** [alik0211/mtproto-core#93]
got this error after a certain time:

TypeError: Cannot read property 'type' of undefined
    at TLDeserializer.rpc_result (/app/telegram/node_modules/@mtproto/core/src/rpc/index.cjs:436:69)
    at TLDeserializer.predicate (/app/telegram/node_modules/@mtproto/core/src/tl/deserializer/index.cjs:163:41)
    at /app/telegram/node_modules/@mtproto/core/src/tl/deserializer/index.cjs:183:28
    at Array.forEach ()
    at TLDeserializer.predicate (/app/telegram/node_modules/@mtproto/core/src/tl/deserializer/index.cjs:165:26)
    at TLDeserializer.predicate (/app/telegram/node_modules/@mtproto/core/src/tl/deserializer/index.cjs:146:26)
    at /app/telegram/node_modules/@mtproto/core/src/tl/deserializer/index.cjs:183:28
    at Array.forEach ()
    at TLDeserializer.predicate (/app/telegram/node_modules/@mtproto/core/src/tl/deserializer/index.cjs:165:26)
    at RPC.handleEncryptedMessage (/app/telegram/node_modules/@mtproto/core/src/rpc/index.cjs:466:38)

**Comment by alik0211** [comment]
This error will probably disappear after the next major version is released.
