### ISSUE TITLE
[QUESTIOn] How to send a message to a user?

### ISSUE THREAD

**Issue by hAbd0u** [alik0211/mtproto-core#97]
I am trying to send a message to user like this:
```
const params = {
  peer: 'Yacmic',
  message: 'Hi Yacmic',
};

mtproto.call('messages.sendMessage', params).then((err, result) => {
	if(err)	
		console.log(`err:`, err);
	else
		console.log(`result:`, result);
}).catch(exception => {
		console.log(`exception:`, exception);
});
```

But unfortunately this what I got when run it:
```
node app
Auth data is located in C:\Users\Mr B\AppData\Local\@mtproto\core\Data
exception: Error: Constructor undefined not found in schema
    at TLSerializer.predicate (Z:\projects\teleflexy2\node_modules\@mtproto\core\src\tl\serializer\index.cjs:136:13)
    at Z:\projects\teleflexy2\node_modules\@mtproto\core\src\tl\serializer\index.cjs:81:12
    at Array.forEach (<anonymous>)
    at TLSerializer.method (Z:\projects\teleflexy2\node_modules\@mtproto\core\src\tl\serializer\index.cjs:68:23)
    at RPC.call (Z:\projects\teleflexy2\node_modules\@mtproto\core\src\rpc\index.cjs:588:29)
    at Z:\projects\teleflexy2\node_modules\@mtproto\core\src\rpc\index.cjs:388:12
    at Array.forEach (<anonymous>)
    at RPC.sendWaitMessages (Z:\projects\teleflexy2\node_modules\@mtproto\core\src\rpc\index.cjs:386:27)
    at RPC.handleTransportOpen (Z:\projects\teleflexy2\node_modules\@mtproto\core\src\rpc\index.cjs:96:12)
```

**Comment by MoJongleur** [comment]
#99
